import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Generated Website',
  description: 'Generated by Website Factory AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}